### ISSUE TITLE
Move to JonasAlfredsson/docker-nginx-certbot

### ISSUE THREAD

**Issue by LoneRifle** [isomerpages/isomer-redirection#135]
docker-nginx-certbot, a Docker image made by @staticfloat , has served us well, allowing us to take advantage of Let's Encrypt certificates without investing too much effort into infrastructure. However, the constraint of having one nginx conf file per FQDN has proven to be tedious as we would often have to specify multiple files per logical group of domains that we wish to redirect.

A fork of docker-nginx-certbot by @JonasAlfredsson allows us to specify multiple FQDNs for one cert/redirection config, which might address this need.

This issue hence covers two tasks:
- [x] Move to the newer fork, and;
- [x] Rewrite the existing .conf in `/letsencrypt` to group FQDNs together

**Comment by JonasAlfredsson** [comment]
Hi,

I got a notification when you mentioned me, so I just wanted to swing by and tell you that you may ask me directly for help if you run into any troubles while testing my version. :)

When transitioning I just want to point out 4 things that might be of interest for you:
1. I do not use `kill -HUP` when [reloading nginx](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/src/scripts/run_certbot.sh#L81). 
2. I do [not override](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/src/Dockerfile#L60) the Nginx parent container's entrypoint, which means that this will run any `*.sh` file found inside the [`/docker-entryoint.d/`](https://github.com/nginxinc/docker-nginx/tree/master/entrypoint) folder.
3. [These](https://github.com/JonasAlfredsson/docker-nginx-certbot/tree/master/src/nginx_conf.d) are the only files present inside the `conf.d/` folder when you pull the image. These can be modified, but I made so that certbot runs in [weboot](https://certbot.eff.org/docs/using.html?highlight=webroot%20path#webroot) mode, which means nginx handles all the web traffic, so the `/.well-known/acme-challenge` location needs to remain somehow.
4. It is possible to manually [trigger a reload](https://github.com/JonasAlfredsson/docker-nginx-certbot#manualforce-renewal) of configs without having to restart the entire container. 

//Jonas

**Comment by staticfloat** [comment]
I also got notified when you mentioned me, and I wanted to just express my admiration for the improvements that Jonas has made on my humble container. :)

**Comment by LoneRifle** [comment]
Thanks to the both of you for your contributions! They have certainly helped the organisations who have used Isomer.

**Comment by LoneRifle** [comment]
Just leaving some logs that indicate that even with Jonas' Docker distribution, Elastic Beanstalk still complains of SIGHUP being sent. I believe `nginx -s reload` uses the signal behind the scenes.
```
2021/03/01 02:27:25.306759 [ERROR] An error occurred during execution of command [app-deploy] - [PreBuildEbExtension]. Stop running the command. Error: EbExtension build failed. Please refer to /var/log/cfn-init.log for more details. 

2021/03/01 02:27:25.307185 [INFO] Executing cleanup logic
2021/03/01 02:27:25.307304 [INFO] CommandService Response: {"status":"FAILURE","api_version":"1.0","results":[{"status":"FAILURE","msg":"Engine execution has encountered an error.","returncode":1,"events":[{"msg":"Instance deployment failed. For details, see 'eb-engine.log'.","timestamp":1614565645,"severity":"ERROR"}]}]}

2021/03/01 02:27:25.307523 [INFO] Platform Engine finished execution on command: app-deploy

2021/03/01 02:30:22.545534 [INFO] Starting...
2021/03/01 02:30:22.545590 [INFO] Starting EBPlatform-PlatformEngine
2021/03/01 02:30:22.545609 [INFO] reading event message file
2021/03/01 02:30:22.545730 [INFO] no eb envtier info file found, skip loading env tier info.
2021/03/01 02:30:22.545815 [INFO] Engine received EB command cfn-hup-exec
```

**Comment by JonasAlfredsson** [comment]
Hmm, that is interesting.
However, if your solution, of only waiting 10 seconds after start of container, solves this issue I would probably just create this file:

#!/bin/bash

# Solves issue with Elastic Beanstalk failing on deploy

# https://github.com/isomerpages/isomer-redirection/issues/133

echo "Sleeping 10 seconds"

sleep 10
echo "Continuing with startup"

And then place it here in the container: /[docker-entrypoint.d](https://github.com/nginxinc/docker-nginx/tree/master/entrypoint)/00-sleeper.sh
This would probably be the easiest fix (so you don't have to overwrite any other files).

//Jonas

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by LoneRifle** [comment]
Thanks for the suggestion! This is now in-place.
